module Templates where

import qualified Text.Printf as P

--configTemplate :: String -> String -> String
configTemplate runDir shareDir repoDir keyDir = 
  P.printf
    "# Autogenerated by pure-install \n\
    \ \n\
    \server { \n\
    \  port      = 3000 \n\
    \  pidFile   = '%s/pure.pid' \n\
    \  logFile   = '/var/log/pure.log' \n\
    \  logLevel  = 'info' \n\
    \  sshClient = '%s/git-ssh-compat' \n\
    \} \n\
    \ \n\
    \repocache { \n\
    \  path = '%s' \n\
    \} \n\
    \ \n\
    \keystore { \n\
    \  path = '%s' \n\
    \} \n\
    \ "
    runDir shareDir repoDir keyDir

systemdServiceTemplate =
  "[Unit] \n\
  \Description=Pure Github Push Relay \n\
  \Documentation=https://github.com/shmookey/pure \n\
  \ \n\
  \[Service] \n\
  \ExecStart=/usr/bin/pure \n\
  \Type=forking \n\
  \PIDFile=/var/run/pure/pure.pid \n\
  \User=pure \n\
  \Group=pure \n\
  \ \n\
  \[Install] \n\
  \WantedBy=multi-user.target \n\
  \ "

