module Templates where

import qualified Text.Printf as P

configTemplate runDir logFile shareDir repoDir keyDir = 
  P.printf
    "# Autogenerated by pure-install \n\
    \ \n\
    \server { \n\
    \  port      = 3000 \n\
    \  pidFile   = \"%s/pure.pid\" \n\
    \  logFile   = \"%s\" \n\
    \  logLevel  = \"info\" \n\
    \  sshClient = \"%s/git-ssh-compat\" \n\
    \} \n\
    \ \n\
    \repocache { \n\
    \  path = \"%s\" \n\
    \} \n\
    \ \n\
    \keystore { \n\
    \  path = \"%s\" \n\
    \} \n\
    \ "
    runDir logFile shareDir repoDir keyDir

systemdServiceTemplate binDir runDir user =
  P.printf
    "[Unit] \n\
    \Description=Pure Github Push Relay \n\
    \Documentation=https://github.com/shmookey/pure \n\
    \ \n\
    \[Service] \n\
    \ExecStart=%s/pure -d \n\
    \Type=forking \n\
    \PIDFile=%s/pure.pid \n\
    \User=%s \n\
    \Group=%s \n\
    \ \n\
    \[Install] \n\
    \WantedBy=multi-user.target \n\
    \ "
    binDir runDir user user

